apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: tf-run
spec:
  outputs:
    resources:
    - name: source
      type: git
  steps:
    - name: list
      image: /usr/
      command: ["/bin/sh"]
      args:
        - "-c"
        - "env"
      env:
        - name: "CUSTOM_BUILD"
          value: "bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2  --cxxopt='-D_GLIBCXX_USE_CXX11_ABI=0' --verbose_failures //tensorflow/tools/pip_package:build_pip_package"
        - name: "BUILD_OPTS"
          value: ""
        - name: "TF_CUDA_VERSION"
          value: "10.0"
        - name: "TF_CUDA_COMPUTE_CAPABILITIES"
          value: "3.0,3.5,5.2,6.0,6.1,7.0"
        - name: "TF_CUDNN_VERSION"
          value: "7"
        - name: "TF_NEED_OPENCL_SYCL"
          value: "0"
        - name: "TF_CUDA_CLANG"
          value: "0"
        - name: "GCC_HOST_COMPILER_PATH"
          value: "/usr/bin/gcc"
        - name: "CUDA_TOOLKIT_PATH"
          value: "/usr/local/cuda"
        - name: "CUDNN_INSTALL_PATH"
          value: "/usr/local/cuda"
        - name: "TF_NEED_JEMALLOC"
          value: "0"
        - name: "TF_GIT_BRANCH"
          value: "r1.15"
        - name: "HOST_ON_HTTP_SERVER"
          value: "n"
        - name: "TEST_WHEEL_FILE"
          value: "y"
        - name: "GIT_RELEASE_REPO"
          value: "https://github.com/AICoE/tensorflow-wheels.git"
        - name: "GIT_TOKEN"
          value: ""
        - name: "GIT_TAG"
          value: ""
        - name: "CUSTOM_TEST"
          value: "bazel test -c opt --local_resources 2048.51.0 -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/lite/..."
        - name: "TF_ENABLE_TEST"
          value: "0"
        - name: "EXTRA_BAZEL_ARGS"
          value: "--host_javabase=@local_jdk//:jdk"
        - name: "DEV_TOOLSET_VERSION"
          value: "8"
        - name: "LOCAL_BUILD"
          value: "y"
        - name: "TF_NEED_GCP"
          value: "0"
        - name: "TF_NEED_VERBS"
          value: "0"
        - name: "TF_NEED_HDFS"
          value: "0"
        - name: "TF_ENABLE_XLA"
          value: "0"
        - name: "TF_NEED_OPENCL"
          value: "0"
        - name: "TF_NEED_CUDA"
          value: "0"
        - name: "TF_NEED_MPI"
          value: "0"
        - name: "TF_NEED_GDR"
          value: "0"
        - name: "TF_NEED_S3"
          value: "0"
        - name: "TF_NEED_KAFKA"
          value: "0"
        - name: "TF_NEED_OPENCL_SYCL"
          value: "0"
        - name: "TF_DOWNLOAD_CLANG"
          value: "0"
        - name: "TF_SET_ANDROID_WORKSPACE"
          value: "0"
        - name: "TF_NEED_AWS"
          value: "0"
        - name: "TF_NEED_TENSORRT"
          value: "0"
        - name: "TF_NEED_ROCM"
          value: "0"
        - name: "TF_NEED_IGNITE"
          value: "0"
        - name: "NCCL_INSTALL_PATH"
          value: "/usr/local/nccl-2.2"
        - name: "TEST_LOOP"
          value: "n"
        - name: "PYTHON_VERSION"
          value: "3.6"
        - name: "BAZEL_VERSION"
          value: "0.24.1"

    - name: tf-manylinux
      image: image-registry.openshift-image-registry.svc:5000/tekton-demo/tf-test:latest
      workingDir: /workspace/
      command: ["/bin/sh"]
      args:
        - "-c"
        - "/usr/libexec/s2i/manylinux2010"
      env:
        - name: "CUSTOM_BUILD"
          value: "bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-mfpmath=both --copt=-msse4.2  --cxxopt='-D_GLIBCXX_USE_CXX11_ABI=0' --verbose_failures //tensorflow/tools/pip_package:build_pip_package"
        - name: "BUILD_OPTS"
          value: ""
        - name: "TF_CUDA_VERSION"
          value: "10.0"
        - name: "TF_CUDA_COMPUTE_CAPABILITIES"
          value: "3.0,3.5,5.2,6.0,6.1,7.0"
        - name: "TF_CUDNN_VERSION"
          value: "7"
        - name: "TF_NEED_OPENCL_SYCL"
          value: "0"
        - name: "TF_CUDA_CLANG"
          value: "0"
        - name: "GCC_HOST_COMPILER_PATH"
          value: "/usr/bin/gcc"
        - name: "CUDA_TOOLKIT_PATH"
          value: "/usr/local/cuda"
        - name: "CUDNN_INSTALL_PATH"
          value: "/usr/local/cuda"
        - name: "TF_NEED_JEMALLOC"
          value: "0"
        - name: "TF_GIT_BRANCH"
          value: "r1.15"
        - name: "HOST_ON_HTTP_SERVER"
          value: "n"
        - name: "TEST_WHEEL_FILE"
          value: "y"
        - name: "GIT_RELEASE_REPO"
          value: "https://github.com/AICoE/tensorflow-wheels.git"
        - name: "GIT_TOKEN"
          value: ""
        - name: "GIT_TAG"
          value: ""
        - name: "CUSTOM_TEST"
          value: "bazel test -c opt --local_resources 2048.51.0 -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/lite/..."
        - name: "TF_ENABLE_TEST"
          value: "0"
        - name: "EXTRA_BAZEL_ARGS"
          value: "--host_javabase=@local_jdk//:jdk"
        - name: "DEV_TOOLSET_VERSION"
          value: "8"
        - name: "LOCAL_BUILD"
          value: "y"
        - name: "TF_NEED_GCP"
          value: "0"
        - name: "TF_NEED_VERBS"
          value: "0"
        - name: "TF_NEED_HDFS"
          value: "0"
        - name: "TF_ENABLE_XLA"
          value: "0"
        - name: "TF_NEED_OPENCL"
          value: "0"
        - name: "TF_NEED_CUDA"
          value: "0"
        - name: "TF_NEED_MPI"
          value: "0"
        - name: "TF_NEED_GDR"
          value: "0"
        - name: "TF_NEED_S3"
          value: "0"
        - name: "TF_NEED_KAFKA"
          value: "0"
        - name: "TF_NEED_OPENCL_SYCL"
          value: "0"
        - name: "TF_DOWNLOAD_CLANG"
          value: "0"
        - name: "TF_SET_ANDROID_WORKSPACE"
          value: "0"
        - name: "TF_NEED_AWS"
          value: "0"
        - name: "TF_NEED_TENSORRT"
          value: "0"
        - name: "TF_NEED_ROCM"
          value: "0"
        - name: "TF_NEED_IGNITE"
          value: "0"
        - name: "NCCL_INSTALL_PATH"
          value: "/usr/local/nccl-2.2"
        - name: "TEST_LOOP"
          value: "n"
        - name: "PYTHON_VERSION"
          value: "3.6"
        - name: "BAZEL_VERSION"
          value: "0.24.1"
