apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tensorflow-build-pipeline
spec:
  resources:
    - name: git-repo
      type: git
    - name: build-image
      type: image
  tasks:
    - name: tensorflow-environment
      taskRef:
        name: build-environment
      params:
        - name: DOCKERFILE
          value: Dockerfile.centos6
        - name: TLSVERIFY
          value: "false"
        - name: DEV_TOOLSET_VERSION
          value: "7"
        - name: BAZEL_VERSION
          value: "2.0.0"
        - name: PYTHON_VERSION
          value: "3.6"
      resources:
        inputs:
          - name: source
            resource: git-repo
        outputs:
          - name: image
            resource: build-image
    - name: tensorflow-build-process
      taskRef:
        name: tensorflow-cpu
      resources:
        inputs:
          - name: build-image
            resource: build-image
        outputs:
          - name: source
            resource: git-repo
      runAfter:
        - tensorflow-environment
