apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: tensorflow-build-pipeline-run
spec:
  serviceAccountName: tensorflow
  pipelineRef:
    name: tensorflow-build-pipeline
  resources:
  - name: git-repo
    resourceRef:
      name: git-repo
  - name: build-image
    resourceRef:
      name: build-image
