---
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: tf-build-pipeline
spec:
  resources:
    - name: git-repo
      type: git
    - name: build-image
      type: image
  tasks:
    - name: tf-build-run
      taskRef:
        name: buildah
      params:
        - name: DOCKERFILE
          value: Dockerfile.centos6
        - name: TLSVERIFY
          value: "false"
        - name: DEV_TOOLSET_VERSION
          value: "7"
        - name: BAZEL_VERSION
          value: "0.24.1"
        - name: PYTHON_VERSION
          value: "3.6"
      resources:
        inputs:
          - name: source
            resource: git-repo
        outputs:
          - name: image
            resource: build-image
    - name: tf-task-run
      taskRef:
        name: tf-run
      resources:
        inputs:
          - name: build-image
            resource: build-image
        outputs:
          - name: source
            resource: git-repo
      runAfter:
        - tf-build-run
