---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: tf-build-pipeline-run
spec:
  serviceAccount: tekton-demo
  pipelineRef:
    name: tf-build-pipeline
  resources:
  - name: git-repo
    resourceRef:
      name: git-repo
  - name: build-image
    resourceRef:
      name: build-image
