# Build pipeline EventListener.
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: build-pipeline-event-listener
spec:
  serviceAccountName: build-pipeline-webhook
  triggers:
    - binding:
        name: build-pipeline-binding
      template:
        name: build-pipeline-template
